sudo: false
notifications:
    email: false
branches:
    only:
        - master
os:
    - linux
language: python
python:
    - '3.5'
    - '3.6'
install:
    - pip install tox-travis
script:
    - tox
